### ISSUE TITLE
Add Me as a Contributor

### ISSUE THREAD

**Issue by JayantGoel001** [App-Choreography/OurContributors#5]
@AvidCoder101 
@CodingSpecies 
Please Add Me as a Contributor Here and send an Invite Link to join this organization.

**Comment by CodingSpecies** [comment]
@all-contributors please add @JayantGoel001  for content, code

**Comment by CodingSpecies** [comment]
I manually added you @JayantGoel001 and invite is sent.

**Comment by JayantGoel001** [comment]
> I manually added you @JayantGoel001 and invite is sent.

I created PR for the Bug 
Check It Once.

**Comment by JayantGoel001** [comment]
Thank You @CodingSpecies
